# Generated by Django 3.1.2 on 2020-12-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertprofile',
            name='degree',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Степень образования'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='education',
            field=models.CharField(blank=True, choices=[('Высшее', 'Высшее'), ('Среднее профессиональное', 'Среднее профессиональное')], default='', max_length=200, null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='interests',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Сфера профессиональных интересов'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Номер телефона для связи'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='position',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Занимаемая должность'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='work_place',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Место работы'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bank',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Банк'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='director_fio',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='ФИО Ген.Директора'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='inn',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Ваш ИНН'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='legal_address',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mail',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Почтовый адрес'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ogrn',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Номер телефона для связи'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rs',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Расчетный счет'),
        ),
    ]
